apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.libraryName }}
  title: ${{ values.libraryName | title }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoOrg }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: ${{ values.repoOrg }}_${{ values.libraryName }}
  tags:
    - nodejs
    - typescript
    - library
    - npm
  links:
    - url: https://www.npmjs.com/package/${{ values.npmScope }}/${{ values.libraryName }}
      title: npm Package
      icon: web
    - url: https://github.com/${{ values.repoOrg }}/${{ values.repoName }}
      title: GitHub
      icon: github
spec:
  type: library
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
