apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.docName }}
  title: ${{ values.docName | title }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoOrg }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - documentation
    - techdocs
    - ${{ values.docType }}
  links:
    - url: https://github.com/${{ values.repoOrg }}/${{ values.repoName }}
      title: GitHub
      icon: github
spec:
  type: documentation
  lifecycle: production
  owner: ${{ values.owner }}
