apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-service-dev
  title: "nginx-service (dev)"
  description: "This will be the server to load the backend APIs"
  annotations:
    harness.io/ci-pipeline-url: "https://app.harness.io/ng/account/M0ul79K-TQWYBL5NkEUxfw/ci/orgs/default/projects/default_project/pipelines/nginx_service_ci/executions/Jk1iKxM1TDirrfEkVU_ANw/pipeline"
    harness.io/ci-pipeline-id: "nginx_service_ci"
    harness.io/cd-pipeline-url: "https://app.harness.io/ng/account/M0ul79K-TQWYBL5NkEUxfw/cd/orgs/default/projects/default_project/pipelines/nginx_service_dev_deploy/executions/v8Wq7mEXSsyTKQPS0atXyw/pipeline"
    harness.io/cd-pipeline-id: "nginx_service_dev_deploy"
    backstage.io/source-location: "url:https://github.com/Ketan-Joshi/nginx-app"
  tags:
    - ecs
    - dev
    - fargate
  links:
    - url: "https://app.harness.io/ng/account/M0ul79K-TQWYBL5NkEUxfw/ci/orgs/default/projects/default_project/pipelines/nginx_service_ci/executions/Jk1iKxM1TDirrfEkVU_ANw/pipeline"
      title: "CI Pipeline (Build & Push)"
      icon: dashboard
    - url: "https://app.harness.io/ng/account/M0ul79K-TQWYBL5NkEUxfw/cd/orgs/default/projects/default_project/pipelines/nginx_service_dev_deploy/executions/v8Wq7mEXSsyTKQPS0atXyw/pipeline"
      title: "CD Pipeline (Deploy - dev)"
      icon: dashboard
    - url: "https://github.com/Ketan-Joshi/nginx-app"
      title: Source Repository
      icon: github
spec:
  type: service
  lifecycle: dev
  owner: "group:default/platform"
  system: ecs-platform
