apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoOrg }}/${{ values.repoName }}
spec:
  type: service
  lifecycle: ${{ values.environment }}
  owner: ${{ values.owner }}
